version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "your-email@example.com"
            git config --global user.name "your-username"
            mkdir gh-pages
            cp -r out/* gh-pages/
            cd gh-pages
            git init
            git remote add origin https://github.com/DulajHansana/My_portfolio-V.01.git
            git checkout -b gh-pages
            git add .
            git commit -m "Deploy to GitHub Pages"
            git push --force origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
